name: polyline_codec
description: Easy way to encoding and decoding a Google Maps Polyline Algorithm for flutter
version: 0.1.4
homepage: https://github.com/everton-e26/polyline_codec

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  fixnum: ^0.10.9
  test: ^1.15.3

dev_dependencies:
  
